defaults: &defaults
  machine: true
  environment:
    GRUNTWORK_INSTALLER_VERSION: v0.0.23
    TERRATEST_LOG_PARSER_VERSION: v0.13.13
    HELM_VERSION: v3.1.2
    MODULE_CI_VERSION: v0.18.4
    TERRAFORM_VERSION: 0.12.7
    TERRAGRUNT_VERSION: NONE
    PACKER_VERSION: NONE
    GOLANG_VERSION: 1.13.8
    K8S_VERSION: v1.10.0
    KUBECONFIG: /home/circleci/.kube/config

install_gruntwork_utils: &install_gruntwork_utils
  name: install gruntwork utils
  command: |
    curl -Ls https://raw.githubusercontent.com/gruntwork-io/gruntwork-installer/master/bootstrap-gruntwork-installer.sh | bash /dev/stdin --version "${GRUNTWORK_INSTALLER_VERSION}"
    gruntwork-install --module-name "gruntwork-module-circleci-helpers" --repo "https://github.com/gruntwork-io/module-ci" --tag "${MODULE_CI_VERSION}"
    gruntwork-install --binary-name "terratest_log_parser" --repo "https://github.com/gruntwork-io/terratest" --tag "${TERRATEST_LOG_PARSER_VERSION}"
    configure-environment-for-gruntwork-module \
      --terraform-version ${TERRAFORM_VERSION} \
      --terragrunt-version ${TERRAGRUNT_VERSION} \
      --packer-version ${PACKER_VERSION} \
      --go-version ${GOLANG_VERSION} \
      --go-src-path test

install_helm_client: &install_helm_client
  name: install helm client
  command: |
    # install helm client
    curl -Lo helm.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz
    tar -xvf helm.tar.gz
    chmod +x linux-amd64/helm
    sudo mv linux-amd64/helm /usr/local/bin/

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - gomod-{{ checksum "test/go.sum" }}

      # Install gruntwork utilities
      - run:
          <<: *install_gruntwork_utils

      - save_cache:
          key: gomod-{{ checksum "test/go.sum" }}
          paths:
            - $HOME/go/src/

      # Fail the build if the pre-commit hooks don't pass. Note: if you run pre-commit install locally, these hooks will
      # execute automatically every time before you commit, ensuring the build never fails at this step!
      - run:
          name: run pre-commit hooks
          command: |
            pyenv global 3.5.2
            pip install pre-commit==1.21.0 cfgv==2.0.1
            pre-commit install
            pre-commit run --all-files

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
            - terraform
            - packer

  test:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /home/circleci
    - checkout
    - run: echo 'export PATH=$HOME/terraform:$HOME/packer:$PATH' >> $BASH_ENV
    - run:
        <<: *install_gruntwork_utils

    # Install helm
    - run:
        <<: *install_helm_client

    - run:
        name: update gcloud
        command: |
          sudo apt-get remove -y google-cloud-sdk
          sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
          sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update beta kubectl
    - run:
        name: configure kubectl
        command: |
          mkdir -p ${HOME}/.kube
          touch ${HOME}/.kube/config
    - run:
        name: run tests
        command: |
          mkdir -p /tmp/logs
          # required for gcloud and kubectl to authenticate correctly
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          # required for terraform and terratest to authenticate correctly
          echo $GCLOUD_SERVICE_KEY > /tmp/gcloud.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcloud.json"
          # run the tests
          run-go-tests --path test --timeout 60m | tee /tmp/logs/all.log
        no_output_timeout: 3600s
    - run:
        command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
        when: always
    - store_artifacts:
        path: /tmp/logs
    - store_test_results:
        path: /tmp/logs

workflows:
  version: 2
  build-and-test:
    jobs:
    - build
    - test:
        requires:
        - build
